# Site settings
title: 'Twin Creeks Church'
description: 'Website for the Twin Creeks Church of Christ'
keyword: 'twincreeks, church, christ'
url: '' # your host

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# if you're using GitHub Pages, set baseurl to your blog's .
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
baseurl: ''

# International
language: zh-cn

# Navigation links
nav:
  home: '/'
  about: '/blog/index.html'
  sermons: '/archives.html'

# Footer
footer:
  since: 2015

# Author
author: 'Twin Creeks Church of Christ'
nickname: 'Twin Creeks Church of Christ'
bio: 'Follow us on Social Media'
avatar: 'assets/img/twincreeks.jpg'

# Search
search: false

# Night mode
nightMode: false

# Comments
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['twitter', 'facebook']

# theme color
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  twitter: 'https://twitter.com/'
  facebook: 'https://facebook.com/'

# CC License
cclicense: true

# CNZZ Analytics
# cnzz: 1234567891
cnzz: 

# Google Analytics
# google_analytics: UA-XXXXXXXXX-X
google_analytics: 

# Build settings
paginate: 10
paginate_path: 'blog/page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md', '*.gemspec', '*.gem']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:categories/:title.html

# Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
